### ISSUE TITLE
Q: Future of this repo

### ISSUE THREAD

**Issue by stevenengland** [iobroker-community-adapters/ioBroker.alias-manager#48]
Hi @sbormann,

first of all thanks for this repo. 

My question: Is this repo still maintained/under development since a few bugs came up since the last commit last year, PRs are not handled. I am new to iobroker and just trying out a few things like Alias Manager and I really like it. But if there will be no more development I shouldn't rely on it :)

**Comment by zoulhh** [comment]
Looks like it is not.

**Comment by mcm1957** [comment]
adapter moved to iobroker-community-adapters
