### ISSUE TITLE
Is this adapter still maintained - PELASE RESPOND UNTIL 30.6.2024

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.alias-manager#51]
@sbormann 

Please let us know whether this adapter is still maintained. As there are some issues and no current activity is visible, the future of this adapter should be decided.

**If there is no reaction until 30.6.2024 we could decide to look for a new maintainer and move this adapter to iobroker-community.**

**Comment by mcm1957** [comment]
Just a kind reminder.
**Please respond until 30.6.2024 with a short note if you plan to maintain this adapter any longer.**

THANK YOU

**Comment by sbormann** [comment]
Hi, sorry for beeing unavailable for such a long time. Please move it to the community. I don't feel i am able to maintain this adapter in the nearby future. Sorry for that and thank you for taking care.

**Comment by mcm1957** [comment]
adapter moved to iobroker-community-adapters
